add Title and alt of images
BANCUNGUYE66/Portofolio.github.io pull request #2
Opened 2023-02-28 13:09 UTC by BANCUNGUYE66

-add page titles
-add image text alternatives

2023-02-28 13:14 UTC, leonardodiasb requested changes
# INVALID ❌ ❌ ❌ 

Hi @BANCUNGUYE66, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - This is a pair-programming exercise and unfortunately, there are no commits from your partner. Please ask your partner to contribute to this exercise as the project required contributions from all the members.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._

2023-03-01 08:48 UTC, wayungi reviewed
Hi @BANCUNGUYE66 , 
![image](https://user-images.githubusercontent.com/99656687/220284938-37e6889a-58a0-4919-8f26-3ddb15647aec.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

You have submitted a project that is invalid because of the following

- [ ] Delete all lines starting with `>`. These lines serve to guide you to fill in the document correctly and should be deleted afterward.
- [ ]  Add all the sections of the [README](https://github.com/microverseinc/readme-template) file. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-01 09:33 UTC, BANCUNGUYE66 commented
Hello @wayungi, please can you tell me what to do? i don't understand what to change. thank you!

2023-03-01 11:29 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @BANCUNGUYE66, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Correct use of GitHub flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] Kindly link the points you added following the tutorial in the link below and include the checks even if you did not find issues in your report to make it look professional. As the project required, your report should include all the topics you checked, i.e:
   - [Page titles](https://www.w3.org/WAI/test-evaluate/preliminary/#title)
   - [Image text alternatives** (<img alt="alt text">)](https://www.w3.org/WAI/test-evaluate/preliminary/#images)
   - [Text headings](https://www.w3.org/WAI/test-evaluate/preliminary/#headings)
   - [Color contrast](https://www.w3.org/WAI/test-evaluate/preliminary/#contrast)
   - [Resize](https://www.w3.org/WAI/test-evaluate/preliminary/#resize)
   - [Interaction](https://www.w3.org/WAI/test-evaluate/preliminary/#interaction) (labels are optional but recommended as voiceover tools can read them, and should be set as invisible to match the Figma design)
   - [Moving content](https://www.w3.org/WAI/test-evaluate/preliminary/#moving)
   - [Multimedia](https://www.w3.org/WAI/test-evaluate/preliminary/#media)
   - [The basic structure of the page](https://www.w3.org/WAI/test-evaluate/preliminary/#structure)
 - If everything was ok, you should make a statement about that (e.g. "Page titles - no issues found").
 - If issues were found, you should [link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 11:29 UTC, leonardodiasb commented on index.html
> +                <a href="#"> <h1 class="logo-h1">Aima.b</h1></a>
- [ ] The logo is correct in the navbar but the logo is not a `heading` tag. Please take a look [at this article](https://www.w3.org/WAI/test-evaluate/preliminary/#headings) to understand better the hierarchy and the use of the `heading` tags and [this one](https://www.reliablesoft.net/h1-tag/) to understand better the use of the `h1` tag. The page should have one but no more than one `h1` tag. Kindly remove it for better SEO and semantics.

2023-03-02 07:24 UTC, hasnatali1947 reviewed
Change review ♻️ 
Please check my comments below and make as required changes.

Submit a re-review when you are done.

thanks 😄

2023-03-02 07:24 UTC, hasnatali1947 commented on index.html
>                    </div>
please consider wrapping all the **li tag** with **ul tage** to make it semantically correct 👍

2023-03-02 07:24 UTC, hasnatali1947 commented on index.html
>                 </div>
kindly you remove the button from **div** it will be semantically correct 👍

2023-03-02 08:23 UTC, closed without merging